### ISSUE TITLE
Calibration functions are not working properly.

### ISSUE THREAD

**Issue by bhavindarji** [marcojonudo/MPU9250_YawAngle#1]
Your program [MPU9250_YawAngle.ino](https://github.com/marcojonudo/MPU9250_YawAngle/blob/master/MPU9250_YawAngle/MPU9250_YawAngle.ino) is working fine with those accelBias,gyroBias,magBias and magScale constant values, but if I use calibration functions instead then I am not getting proper Roll, Pitch and Yaw output. How did you get those values...?

**Comment by marcojonudo** [comment]
Hi @bhavindarji !

I'm glad you find this project useful. Even when it's been quite a long time since I left this project, I will try to help you as much as possible.
Calibration values for accelerometer and gyroscope are easy to get, as leaving the board alone and still in a table is enought to get them. Nevertheless, I found magnetometer ones a lot more confusing.
Even when most of the tutorials I saw recommended making 'eight shapes' in the air, I found this was not enough to get correct values. I needed to not only move the sensor like this, only in an 'eight shape' in two dimensions, but also drawing a sphere in the air. All this while turning the wrist in different directions.

To ensure the got values are correct, you can output them and paint them with a software like Matlab. The objective is to get something like the picture attached.
![calibrated_magnetometer](https://user-images.githubusercontent.com/8701491/38081811-3e8fc3c0-3345-11e8-8412-de7266c4a449.png)

I found this quite complex to explain, as some time has passed and this is a confusing topic. If you understand some spanish, I suggest you have a look at the whole document of my application: https://github.com/marcojonudo/ZowiApp/blob/master/document/TFM_ZowiApprende_MarcoMartinezAvila.pdf (section 8.10.4). There, I expose more details about the whole process of using the MPU9250.

I hope these tips point you in the right direction.

Best regards!

**Comment by bhavindarji** [comment]
Thank you for the explanation...
I Don't understand Spanish but with the help of google translate I think I will... ☺️ 
Thanks for the help again...
